sudo: required
dist: trusty
language: generic

install:
- sudo add-apt-repository ppa:gert-die/trusty-mia -y 
- sudo apt-get update -qq
- sudo apt-get install -y libmaxflow-dev libdcmtk2-dev libeigen3-dev libfftw3-dev libgsl0-dev libgts-dev libhdf5-dev libitpp-dev libnifti-dev libnlopt-dev libopenexr-dev libpng-dev libtbb-dev libtiff-dev libvtk6-dev libvistaio-dev libxml++2.6-dev python-lxml xsltproc docbook-xsl doxygen doxygen-latex graphviz libblas-dev libboost-filesystem-dev libboost-regex-dev libboost-serialization-dev libboost-system-dev libboost-test-dev

before_script:
- mkdir build
- cd build
- cmake .. -DALWAYS_CREATE_DOC=ON -DSTRICT_DEPENDECIES=ON -DMIA_CREATE_MANPAGES=ON -DMIA_CREATE_NIPYPE_INTERFACES=ON
script:
- make -j2
after_success:
- make test
env:
  global:
  - secure: GJh7knKOeyjofQFswCHI4H1VeRBYDmGrZjBiW/yNoGqLvvAZi32HF2d5gHj2vrsGBqto/5mQrydo1rH6Q85VuZ7ZNZmcmiMVA5htv61WKfxzc50mSrkSfvDTb0MOmR8QcpWpK4YAfCYd4r8drPfpbRdHUvTfEk9tS8I/1LGLuos3cLRU+OojEuvndUC8rGHtCRtDswFmngbc96gkAuHfAd7LiaJ5EY+pqOmHY4xMgi5Ev4FnGdkUczUcpisxee/48QIite9lw5E0pemPepKuhrwUJRvnzb9Tgsp94R42mzymvnKyLsttdUQtUItTQshTqEtWSFf/6GO9GPyUXAgR+BDsQ9ODlxOC6+Cip0HqxCvgDfIZarVaj5/2/ZwiyjocEinhSzFiIJF9SShpqSpP9MUgS/ZL/9y6GMiDXx19zkxBJ9kXP+7vH/G/7qFZ6f1aVuDemgKit5styDQDnLyd/FlBrz3oWftj4WDpF3LQIwAAstq1nBKsccYT5cfcbrvMY+lNTAL0HrjAt06C1b9DoG0ftEy5YWYrJlgdfmkXhK9O6Dz73Pj8FMDjJyKlFIpssLWEmQUE3LytnDY3tw7uE+JIXIb8Ii3Q8CLX/IMWjEkHAaXd4+jXJOAoFWelZtCqbHXRH367Rel7ETBmI/PELm3WaGKxcTACC8zpLk9IDJQ=
addons:
  coverity_scan:
    project:
      name: gerddie/mia
      version: 2.2.7+
      description: Medical imaga analysis library
    notification_email: gw.fossdev@gmail.com
    build_command: make -j2
    branch_pattern: coverity_scan
