
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine WORDS_BIGENDIAN 1
#cmakedefine ICA_ALWAYS_USE_SYMM 1 

#cmakedefine BUILD_SSE_ATTRIBUTE_VECTOR_CAN_USE_SUBSCRIPT 1

#cmakedefine ENABLE_DEBUG_MESSAGES 1

#define SOURCE_ROOT "@SOURCE_ROOT@"
#define PLUGIN_SEARCH_PATH  "@PLUGIN_SEARCH_PATH@"
#define PLUGIN_INSTALL_PATH  "@PLUGIN_INSTALL_PATH@"

#cmakedefine LONG_64BIT 1
#cmakedefine HAVE_TBB 1 
