MODULE MIA
DESCRIPTION MIA support routines for IDL
VERSION 1.0
SOURCE Gert Wollny <gert@die.upm.es> Biomedical Imaging Technologies
BUILD_DATE OCT 01 2007
PROCEDURE MIA_SET_TEST 0 0
PROCEDURE MIA_DEBUG 0 0
FUNCTION MIA_DEBUG_LEVEL 1 1
FUNCTION MIA_ECHO 1 1
FUNCTION MIA_FILTER2D 2 2
FUNCTION MIA_FILTER3D 2 2
FUNCTION MIA_NRREG2D 8 8 
FUNCTION MIA_DEFORM2D 3 3 
FUNCTION MIA_NRREG3D 8 8 
FUNCTION MIA_DEFORM3D 3 3 
FUNCTION MIA_READ2DIMAGE 1 1 
