

FIND_PROGRAM(MKOCTFILE mkoctfile)
IF(MKOCTFILE_FOUND)

  EXECUTE_PROCESS(COMMAND ${MKOCTFILE} -p INCFLAGS    RESULT_VARIABLE R1 OUTPUT_VARIABLE OCT_INCLUDES)
  EXECUTE_PROCESS(COMMAND ${MKOCTFILE} -p LDFLAGS     RESULT_VARIABLE R2 OUTPUT_VARIABLE OCT_FDFLAGS)
  EXECUTE_PROCESS(COMMAND ${MKOCTFILE} -p OCTAVE_LIBS RESULT_VARIABLE R3 OUTPUT_VARIABLE OCTAVE_LIBS)
  EXECUTE_PROCESS(COMMAND ${MKOCTFILE} -p BLAS_LIBS   RESULT_VARIABLE R4 OUTPUT_VARIABLE BLAS_LIBS) 
  EXECUTE_PROCESS(COMMAND ${MKOCTFILE} -p FFTW_LIBS   RESULT_VARIABLE R5 OUTPUT_VARIABLE FFTW_LIBS)
  EXECUTE_PROCESS(COMMAND ${MKOCTFILE} -p LIBS        RESULT_VARIABLE R6 OUTPUT_VARIABLE LIBS)
  
  IF (R1 AND R2 AND R3 AND R4 AND R5 AND R6)
    SET(OCTAVE_FOUND TRUE)
    SET(OCTAVE_INCLUDES ${OCT_INCLUDES})
    SET(OCTAVE_LIBS ${OCT_FDFLAGS} ${OCTAVE_LIBS} ${BLAS_LIBS} ${FFTW_LIBS} ${LIBS})
    SET(OCTAVE_SUFFIX "oct")
    SET(OCTAVE_PREFIX "")
  ENDIF(R1 AND R2 AND R3 AND R4 AND R5 AND R6 AND R7)

ENDIF(MKOCTFILE_FOUND)
